site_name: Finn Documentation

nav:
  - Home: index.md
  - About: about.md
  - Food: food.md

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  logo: assets/finn.png
  favicon: assets/images/favicon.ico
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.path

  palette:

    - scheme: finn-light
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
    
    - scheme: finn-dark
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

extra:
  homepage: https://johnthompson.io/mkdocs-learning/
