site_name: Finn-structions
site_url: https://johnthompson.io/finnstructions/
repo_url: https://github.com/JohnMThompson/finnstructions
repo_name: Visit our GitHub repo!
site_author: John Thompson
site_description: A fun site I'm building to learn MkDocs
copyright: John Thompson

nav:
  - Home: index.md
  - About Finn:
    - Finn's Story: story.md
    - Stats: about.md
  - Food:
    - Meals: food.md
    - Treats and Chews: treats.md
  - Healthcare:
    - Medications: meds.md
    - Grooming: grooming.md
  - Activities:
    - Walks & Outdoor Time: walk.md
    - Sleeping Arrangements: sleep.md
    - Typical Day: typical-day.md
  - I'm done with Finn-structions:
    - Return to johnthompson.io: return.md


extra_css:
  - stylesheets/extra.css

theme:
  name: material
  logo: assets/finn.png
  favicon: assets/images/favicon.ico
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tracking
  #   - navigation.tabs
  #   - navigation.tabs.sticky
    - navigation.sections
  #   - navigation.path

  palette:

    - scheme: finn-light
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
    
    - scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
      primary: custom

extra:
  homepage: https://johnthompson.io/finnstructions/
